config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'daniel', password:'1234', only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About'
    @content = 'this is the about page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'daniel', password:'1234', expect: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    # pegar um único post
    @post = Post.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    # Post - vai representar o modelo
    @post = Post.new(post_params)

    # salvar
    if (@post.save)
      # vai carregar o show view.
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if (@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  # definimos uma obrigatoriedade agora para o modelo
  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comentários </h3>
<% @post.comments.each do |comment| %>
  <div class="card card-body">
    <p><strong><%= comment.username%></strong> : <%= comment. body %><%= link_to "[x]", [comment.post, comment], method: :delete, data: {confirm: 'Você tem certeza?'}, :class => 'text-secondary' %></p>

  </div>

<% end %>

app/views/comments/_form.html.erb
<h3> Adicionando Comentários </h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <div>
    <%= f.submit({:class=>"btn btn-light"})%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IniTodo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container d-flex justify-content-between">
        <a href="" class="navbar-brand d-flex align-items-center">
          <svg style="left: 20px ;position: absolute;border-radius: 35%;" width="50px" height="50px" enable-background="new 0 0 426.667 426.667" version="1.1" viewbox="0 0 426.667 426.667" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
            <g fill="#fff">
              <path
                d="m170.67 128l-69.333 69.333c6.613 2.56 11.947 5.653 16.427 8.32 7.893 4.8 12.693 7.68 24.533 7.68s16.64-2.88 24.533-7.573c9.6-5.76 22.827-13.76 46.507-13.76s36.907 7.893 46.507 13.76c7.893 4.8 12.693 7.573 24.533 7.573s16.64-2.88 24.533-7.573c2.56-1.6 5.44-3.2 8.64-4.907l-136.64-136.85c-33.174-33.174-63.574-42.88-116.91-42.667v53.333c38.827-0.213 61.547 8.32 85.333 32l21.334 21.334z"/>
              <path
                d="m401.92 259.1c-9.6-5.867-22.827-13.76-46.507-13.76s-36.907 8-46.507 13.76c-7.893 4.693-12.693 7.573-24.533 7.573s-16.64-2.773-24.533-7.573c-9.6-5.867-22.827-13.76-46.507-13.76s-36.907 8-46.507 13.76c-7.893 4.693-12.693 7.573-24.533 7.573-11.947 0-16.747-2.88-24.64-7.68-9.6-5.76-22.827-13.653-46.507-13.653s-36.907 7.893-46.507 13.653c-8 4.8-12.8 7.68-24.64 7.68v42.667c23.68 0 36.907-7.893 46.507-13.653 8-4.8 12.693-7.68 24.64-7.68s16.747 2.88 24.64 7.68c9.6 5.76 22.827 13.653 46.507 13.653s36.907-7.893 46.72-13.76c7.893-4.693 12.693-7.573 24.533-7.573s16.64 2.773 24.533 7.573c9.6 5.867 22.827 13.76 46.507 13.76s36.907-8 46.507-13.76c7.893-4.693 12.693-7.573 24.533-7.573s16.64 2.88 24.533 7.573c9.6 5.867 22.827 13.76 46.507 13.76v-42.667c-11.839 0-16.639-2.88-24.746-7.573z"/>
              <path
                d="m355.41 341.34c-23.68 0-36.907 8-46.507 13.76-7.893 4.693-12.693 7.573-24.533 7.573s-16.64-2.773-24.533-7.573c-9.6-5.867-22.827-13.76-46.507-13.76s-36.907 8-46.507 13.76c-7.893 4.693-12.693 7.573-24.533 7.573-11.947 0-16.747-2.88-24.64-7.68-9.6-5.76-22.827-13.653-46.507-13.653s-36.907 7.893-46.507 13.653c-8 4.8-12.8 7.68-24.64 7.68v42.667c23.68 0 36.907-7.893 46.507-13.653 8-4.8 12.693-7.68 24.64-7.68s16.747 2.88 24.64 7.68c9.6 5.76 22.827 13.653 46.507 13.653s36.907-7.893 46.72-13.76c7.893-4.693 12.693-7.573 24.533-7.573s16.64 2.773 24.533 7.573c9.6 5.867 22.827 13.76 46.507 13.76s36.907-8 46.507-13.76c7.893-4.693 12.693-7.573 24.533-7.573s16.64 2.88 24.533 7.573c9.6 5.867 22.827 13.76 46.507 13.76v-42.667c-11.84 0-16.64-2.88-24.747-7.573-9.599-5.867-22.826-13.76-46.506-13.76z"/>
            </g>
            <circle cx="309.33" cy="74.668" r="53.333" fill="#fff"/>
          </svg>
          <strong style="margin: 10px 10px"> #todo</strong>
        </a>
        <div class="row">
          <div class="col-md-6">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", home_path %></li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Novo Item", new_post_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
  <style media="screen">
    a {
      color: white;
    }

    *{
      font-family: monospace;
    }
  </style>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>

<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="text-muted">
  <p> Insira um nova coisa para ser feita </p>
</div>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
  <p>
    <%= f.label :Titulo %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Contéudo %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <div>
    <%= f.submit({:class=>"btn btn-warning"})%>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Todo List</h1>

<% @posts.each do |post| %>
  <div class="card card-body bg-light">
    <div class="row">
      <div class="col-md-12">
        <h3><%= post.title %></h3>
        <div class="card card-body">
          <p><%= post.body %></p>
        </div>
        <%= link_to "lê apenas esse", post_path(post), :class => 'btn-right btn-sm btn-dark' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Novo Post</h1>
<div class="text-muted">
  <p> Insira um nova coisa para ser feita </p>
</div>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
  <p>
    <%= f.label :Titulo %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Contéudo %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
  </p>
  <div>
    <%= f.submit({:class=>"btn btn-warning"})%>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="card card-body">
  <div class="text-center">
    <h2><%= @post.title %></h2>
  </div>
  <p><%= @post.body %></p>
</div>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-light' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Você tem certeza? "}, :class => 'btn btn-danger' %>

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>